import jsPDF from "jspdf";

interface Recommendation {
  topic: string;
  advice: string;
  resource_title: string;
  resource_url: string;
}

interface GradeData {
  score: number;
  strengths: string[];
  weaknesses: string[];
  actionable_feedback: string;
  recommendations?: Recommendation[];
}

interface Submission {
  title: string;
  _creationTime: number;
  gradeData?: GradeData;
}

export const generateAuditPDF = (submission: Submission) => {
  const doc = new jsPDF();
  const lineHeight = 7;
  let cursorY = 20;
  
  // 1. Defined here once. Do not redeclare later.
  const pageHeight = doc.internal.pageSize.height; 

  // Helper to check for new page
  const checkPageBreak = (neededSpace: number = 20) => {
    if (cursorY + neededSpace > pageHeight - 20) {
        doc.addPage();
        cursorY = 20;
    }
  };

  const addText = (text: string, x: number, fontSize: number = 10, font: string = "helvetica", style: string = "normal") => {
    doc.setFont(font, style);
    doc.setFontSize(fontSize);
    doc.text(text, x, cursorY);
    cursorY += lineHeight;
  };

  const addLine = () => {
    cursorY += 2;
    doc.setDrawColor(200, 200, 200); 
    doc.line(20, cursorY, 190, cursorY);
    cursorY += 10;
  };

  // --- HEADER ---
  addText("DESIGN_VISION_AI // OFFICIAL REPORT", 20, 8, "courier", "bold");
  cursorY += 5; 
  
  addText(`PROJECT: ${submission.title.toUpperCase()}`, 20, 14, "helvetica", "bold");
  addText(`DATE: ${new Date(submission._creationTime).toLocaleDateString().toUpperCase()}`, 20, 10, "helvetica", "normal");
  
  if (submission.gradeData) {
    const score = submission.gradeData.score;
    addText(`AUDIT SCORE: ${score}/100`, 150, 14, "courier", "bold");
  }

  addLine();

  // --- CONTENT ---
  if (submission.gradeData) {
    const { strengths, weaknesses, actionable_feedback, recommendations } = submission.gradeData;

    // Strengths
    addText("01 // STRENGTHS", 20, 10, "courier", "bold");
    cursorY += 2;
    strengths.forEach((point) => {
        const lines = doc.splitTextToSize(`+ ${point}`, 170);
        lines.forEach((line: string) => {
            checkPageBreak();
            addText(line, 20, 10, "helvetica", "normal");
        });
    });
    cursorY += 5;

    // Weaknesses
    checkPageBreak();
    addText("02 // WEAKNESSES", 20, 10, "courier", "bold");
    cursorY += 2;
    weaknesses.forEach((point) => {
        const lines = doc.splitTextToSize(`- ${point}`, 170);
        lines.forEach((line: string) => {
             checkPageBreak();
             addText(line, 20, 10, "helvetica", "normal");
        });
    });
    
    addLine();

    // Director's Note
    checkPageBreak();
    addText("03 // DIRECTOR'S NOTE", 20, 10, "courier", "bold");
    cursorY += 2;
    const feedbackLines = doc.splitTextToSize(actionable_feedback, 170);
    feedbackLines.forEach((line: string) => {
        checkPageBreak();
        addText(line, 20, 10, "times", "italic");
    });

    // Recommendations
    if (recommendations && recommendations.length > 0) {
        addLine();
        checkPageBreak();
        addText("04 // RECOMMENDATIONS & RESOURCES", 20, 10, "courier", "bold");
        cursorY += 2;

        recommendations.forEach((rec) => {
            checkPageBreak(30); 
            
            // Topic
            addText(`TOPIC: ${rec.topic.toUpperCase()}`, 20, 9, "helvetica", "bold");
            
            // Advice
            const adviceLines = doc.splitTextToSize(rec.advice, 170);
            adviceLines.forEach((line: string) => addText(line, 20, 9, "helvetica", "normal"));
            
            // Source
            doc.setTextColor(100, 100, 100);
            addText(`SOURCE: ${rec.resource_title} (${rec.resource_url})`, 20, 8, "courier", "normal");
            doc.setTextColor(0, 0, 0); 
            
            cursorY += 4; 
        });
    }
  }

  // --- FOOTER (FIXED) ---
  // We reuse 'pageHeight' defined at the top
  cursorY = pageHeight - 20; 
  
  doc.setDrawColor(200, 200, 200); 
  doc.line(20, cursorY - 5, 190, cursorY - 5); 

  doc.setFontSize(8);
  doc.setFont("courier", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("GENERATED BY AUDIT_AI", 20, cursorY);
  
  // Jet Noir Link
  doc.setTextColor(0, 0, 0); // Black text
  const linkText = "BUILT BY JET NOIR SYSTEMS";
  const linkX = 140;
  
  doc.text(linkText, linkX, cursorY);
  // Add clickable area over the text
  doc.link(linkX, cursorY - 3, 50, 5, { url: "https://www.jetnoir.systems/" });

  doc.save(`audit_report_${submission.title.replace(/\s+/g, "_").toLowerCase()}.pdf`);
};